version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install time
      - export BUCKET=crosstalk-lambda-artifacts
      - aws cloudformation package --template-file template.yaml --s3-bucket crosstalk-lambda-artifacts  --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml
